# Generated by Django 6.0.7 on 2026-08-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
