# Generated by Django 6.0.7 on 2026-08-09 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_assigned_to_task_assigned_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdeliverable',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskdeliverable',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskdeliverable',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_deliverables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('reviewing', 'Under Review'), ('quoted', 'Quote Sent'), ('accepted', 'Quote Accepted'), ('paid', 'Paid'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='submitted', max_length=30),
        ),
    ]
