# Generated by Django 6.0.7 on 2026-09-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_task_description_alter_taskdocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdocument',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
